export const path = {
    register: '/api/auth/signup',
    login: '/api/auth/signin',
    resetPass: "/api/auth/reset-password",
    verifyPath: "/api/auth/reset-verify",
    getLists: `/api/seri`,
    createList: `/api/admin/series/`,
    updateList: (id) => `/api/admin/series/${id}`,
    deleteList: (id) => `/api/admin/series/${id}`,
    getMovies: `/api/movie`,
    createMovie: `/api/admin/movies/`,
    updateMovie: (id) => `/api/admin/movies/${id}`,
    activeMovie: (id, status) => status ? `/api/admin/movies/${id}/hide` : `/api/admin/movies/${id}/show`,
    deleteMovie: (id) => `/api/admin/movies/${id}`,
    getCategories: `/api/category/`,
    addReview: `/api/review`,
    deleteReview: (id) => `/api/review/${id}`,
    updateInfoUser: `/api/user`,
    getPlan: `/api/plan`,
    getChat: `/api/chat`,
    createCategory: `/api/admin/categories/`,
    deleteCategory: (id) => `/api/admin/categories/${id}`,
    updateCategory: (id) => `/api/admin/categories/${id}`,
    getPlans: `/api/plans/`,
    createPlan: `/api/admin/plans/`,
    deletePlan: (id) => `/api/admin/plans/${id}`,
    updatePlan: (id) => `/api/admin/plans/${id}`,
    billing: `/api/billing`,
}